//
//  SlicerToGCode.cpp
//  Bridges ofxSlicer output (Layer contours) to G-code string generation.
//

#include "SlicerToGCode.h"
#include <sstream>
#include <iomanip>
#include <cmath>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

//--------------------------------------------------------------
float SlicerToGCode::computeExtrusionLength(float moveLength, float layerHeight) const {
    // Cross-section of deposited bead: nozzleDiameter * layerHeight (rectangular approximation)
    // Filament cross-section: PI * (filamentDiameter/2)^2
    float beadArea = nozzleDiameter * layerHeight;
    float filamentArea = (float)M_PI * (filamentDiameter * 0.5f) * (filamentDiameter * 0.5f);
    if (filamentArea < 1e-6f) return 0.0f;
    return (beadArea * moveLength / filamentArea) * extrusionMultiplier;
}

//--------------------------------------------------------------
void SlicerToGCode::emitContour(std::ostringstream& out, const ofPolyline& contour,
                                 float z, float& currentE, glm::vec3& currentPos, bool& atSafeZ)
{
    auto& verts = contour.getVertices();
    if (verts.size() < 2) return;

    // Travel to start of contour
    glm::vec3 start(verts[0].x, verts[0].y, z);

    if (cncMode) {
        // CNC: retract to safeZ, rapid to start XY, plunge to Z
        if (!atSafeZ) {
            out << "G0 Z" << std::fixed << std::setprecision(3) << safeZ << "\n";
            atSafeZ = true;
        }
        out << "G0 X" << start.x << " Y" << start.y
            << " F" << std::setprecision(0) << travelFeedRate << "\n";
        out << std::setprecision(3);
        out << "G1 Z" << z << " F" << std::setprecision(0) << plungeFeedRate << "\n";
        out << std::setprecision(3);
        atSafeZ = false;
    } else {
        // 3D printing: move to start XY at current Z, then set Z
        bool needTravel = (glm::distance(glm::vec2(currentPos), glm::vec2(start)) > 0.01f);
        if (needTravel) {
            out << "G0 X" << start.x << " Y" << start.y
                << " F" << std::setprecision(0) << travelFeedRate << "\n";
            out << std::setprecision(3);
        }
        if (std::abs(currentPos.z - z) > 0.001f) {
            out << "G0 Z" << z << "\n";
        }
    }
    currentPos = start;

    // Cut/print along contour vertices
    for (size_t i = 1; i < verts.size(); i++) {
        glm::vec3 pt(verts[i].x, verts[i].y, z);
        float moveLen = glm::distance(glm::vec2(currentPos), glm::vec2(pt));

        if (cncMode) {
            out << "G1 X" << pt.x << " Y" << pt.y
                << " F" << std::setprecision(0) << feedRate << "\n";
            out << std::setprecision(3);
        } else {
            currentE += computeExtrusionLength(moveLen, printLayerHeight);
            out << "G1 X" << pt.x << " Y" << pt.y
                << " E" << std::setprecision(4) << currentE
                << " F" << std::setprecision(0) << feedRate << "\n";
            out << std::setprecision(3);
        }
        currentPos = pt;
    }

    // Close the contour if marked as closed
    if (contour.isClosed() && verts.size() > 2) {
        glm::vec3 pt(verts[0].x, verts[0].y, z);
        float moveLen = glm::distance(glm::vec2(currentPos), glm::vec2(pt));
        if (moveLen > 0.001f) {
            if (cncMode) {
                out << "G1 X" << pt.x << " Y" << pt.y
                    << " F" << std::setprecision(0) << feedRate << "\n";
                out << std::setprecision(3);
            } else {
                currentE += computeExtrusionLength(moveLen, printLayerHeight);
                out << "G1 X" << pt.x << " Y" << pt.y
                    << " E" << std::setprecision(4) << currentE
                    << " F" << std::setprecision(0) << feedRate << "\n";
                out << std::setprecision(3);
            }
            currentPos = pt;
        }
    }
}

//--------------------------------------------------------------
std::string SlicerToGCode::generateGCodeString(const std::vector<Layer>& layers) {
    std::ostringstream out;
    out << std::fixed << std::setprecision(3);

    // Header
    out << "; Generated by ofxSlicer + ofxGCode\n";
    out << "; Layers: " << layers.size() << "\n";
    out << "G21 ; mm mode\n";
    out << "G90 ; absolute positioning\n";

    if (!cncMode) {
        out << "M82 ; absolute extrusion\n";
        out << "G28 ; home all axes\n";
    }

    out << "G0 Z" << safeZ << " F" << std::setprecision(0) << travelFeedRate << "\n";
    out << std::setprecision(3);
    out << "G0 X0 Y0\n";

    glm::vec3 currentPos(0, 0, safeZ);
    float currentE = 0;
    bool atSafeZ = true;

    for (size_t li = 0; li < layers.size(); li++) {
        const auto& layer = layers[li];
        float z = layer.layerHeight;

        out << "\n; Layer " << li << " Z=" << z << "\n";

        // Perimeters (contours) first
        for (const auto& contour : layer.contours) {
            emitContour(out, contour, z, currentE, currentPos, atSafeZ);
        }

        // Infill (jobs) second
        for (const auto& job : layer.jobs) {
            emitContour(out, job.contour, z, currentE, currentPos, atSafeZ);
        }
    }

    // Footer
    out << "\n";
    if (cncMode) {
        out << "G0 Z" << safeZ << "\n";
        out << "G0 X0 Y0\n";
    } else {
        out << "M104 S0 ; turn off hotend\n";
        out << "M140 S0 ; turn off bed\n";
        out << "G28 X0 Y0 ; home X/Y\n";
        out << "M84 ; disable motors\n";
    }
    out << "M2 ; end program\n";

    return out.str();
}
